pipeline {
  agent any
  stages {
    stage('Build') {
      steps {
        // Clones the repository from the current branch name
        echo 'Make the output directory'
        sh 'mkdir -p build'

        echo 'Cloning files from (branch: "' + branchName + '" )'
        dir('build') {
            git branch: branchName, credentialsId: 	gitCredentials, url: git 'https://github.com/bcalvessilva/firstnewmanexample'
        }
      }      
    }
  }
}
