pipeline {
  agent any
 
  tools {nodejs "node_18.7.0"}
 
  stages {
    stage('Download Git Repository') {
      steps {
        git branch: 'aula_12_final_result', url: 'https://github.com/bcalvessilva/firstnewmanexample.git'
      }
    }
    stage('Run') {
      steps {
        sh 'newman run third/AULA_09.postman_collection.json -e third/AULA_09.postman_environment.json -d third/AULA_09-users.json --reporters cli,htmlextra --reporter-htmlextra-export "newman_result.html"'
        publishHTML target: [
            allowMissing: false,
            alwaysLinkToLastBuild: false,
            keepAll: true,
            reportDir: '.',
            reportFiles: 'newman_result.html',
            reportName: 'Newman HTML Reporter'
        ]
      }
    }
  }
}